# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.0"

# By default this VM will use 2 processor cores and 2GB of RAM. The 'VM_CPUS' and
# "VM_RAM" environment variables can be used to change that behaviour.
cpus = ENV["VM_CPUS"] || 2
ram = ENV["VM_RAM"] || 2048

Vagrant.configure(2) do |config|

  config.vm.box = "baunegaard/win10pro-en"
  config.vm.guest = :windows

  config.vm.communicator = "winrm"
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.vm.network :public_network, :bridge => "wlp6s0"
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct:true
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "rdp", auto_correct:true

  config.vm.provider :vmware_workstation do |vm|
    vm.gui = true
  end

  config.vm.provision "shell", inline: <<-SHELL1
    Set-ExecutionPolicy Bypass -Scope Process -Force; iwr -useb get.scoop.sh | iex
    scoop bucket add extras
    scoop bucket add java
    scoop install sudo
    scoop install chromium
    scoop install win32-openssh
    scoop install vim
    scoop install xmlstarlet
    scoop install curl
    scoop install which
  SHELL1


  config.vm.provision "shell", inline: <<-SHELL2
    Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    choco install firefox -y
    choco install openjdk8  -y
  SHELL2

end