# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.synced_folder "~/vagrant-stuff", "/vagrant_stuff"

  config.vm.provider "vmware-desktop" do |v|
     v.gui = true
     v.memory = "4096"
   end

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y && apt-get dist-upgrade -y
     apt-get install -y openssh-server tmux openssl wget curl nano ifupdown resolvconf
   SHELL
end